#!/bin/bash

function link_files {
	 local source="${1}"
	 local target="${2}"
	 if [ ! -f ${target} ]; then
	     ln -s ${source} ${target}
	 fi
}
link_files ~/dotfiles/.tmux.conf ~/.tmux.conf
link_files ~/dotfiles/.gitconfig ~/.gitconfig
link_files ~/dotfiles/.vimrc ~/.vimrc

if [ ! -d "~/.vim/plugins" ]; then
   mkdir -p ~/.vim/plugins
fi

if [ ! -d "~/.vim/colors" ]; then
    mkdir -p ~/.vim/colors
fi
link_files ~/dotfiles/vimplugins/harlequin.vim ~/.vim/colors/harlequin.vim
